### ISSUE TITLE
get AttributeError: 'DataFrame' object has no attribute 'map' while running blog example

### ISSUE THREAD

**Issue by ronamadthis** [ajayarunachalam/msda#1]
AttributeError                            Traceback (most recent call last)
<ipython-input-15-77b2dcd686d8> in <module>
----> 1 FeatureSelection.plot(df, logging_interval=2)

c:\users\sitra\anaconda3\envs\pythondata\lib\site-packages\msda\msda.py in plot(df, logging_interval)
    410         cols = list(df.columns)[2:]
    411         #columns = df.iloc[:,2:].values.tolist()
--> 412         columns =  df.iloc[:,2:].aggregate(lambda x: [x.tolist()], axis=0).map(lambda x:x[0])
    413         time_min = []
    414         initial=0

c:\users\sitra\anaconda3\envs\pythondata\lib\site-packages\pandas\core\generic.py in __getattr__(self, name)
   5137             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5138                 return self[name]
-> 5139             return object.__getattribute__(self, name)
   5140 
   5141     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'map'

I have python 3.6.2 and pandas 1.1.4

**Comment by ajayarunachalam** [comment]
This error is due to the deprecation of map function in pandas version > 1.0.5. A quick hack would be to test it with the same environment that I have tested it on. I will fix this with next version of the package release.

**Comment by lironsam** [comment]
Any news of this ?
