### ISSUE TITLE
ZeroDivisionError 

### ISSUE THREAD

**Issue by zay3d** [ajayarunachalam/msda#2]
while executing *print Ratios of Variations of Values in each column*
my df had initially zeros and removed it, still it shows the same error below

![Screen Shot 2021-07-01 at 12 57 08 AM](https://user-images.githubusercontent.com/63463469/124037413-32189f00-da08-11eb-9a0a-4d8b50468cb3.png)

**Comment by ajayarunachalam** [comment]
Try replacing the zero value with integer type & see if it works. I will handle this exception in the next version of the release.

**Comment by ajayarunachalam** [comment]
@zay3d : Can you share a snippet of your data? I can check quickly.

**Comment by zay3d** [comment]
*Workaround by adding +1 to denominator  (V2/V1+1)

**Comment by ajayarunachalam** [comment]
Okay, thanks for informing & glad that the hack worked. I will update this with the next release.
