### ISSUE TITLE
Why is the deepCNN model used when finding exceptions and another model built by keras used when interpreting the model (XAI)?

### ISSUE THREAD

**Issue by xuezhenzhu** [ajayarunachalam/msda#3]
I've been studying this project recently and have doubts about **model interpretation**. In MSDA / blog_ Example / unsupervised-deep-analog-detector-with-interpretable-results.ipynb, which uses the deepcnn or lstmaenn model to train and find exceptions, but the interpretable results of the exception detector use a new model built by keras. This model seems to have nothing to do with the previous exception detection model.
Can you give me some explanations or references? Thank you very much for any reply.

**Comment by ajayarunachalam** [comment]
Hi. Yes, that's absolutely right. In this particular case the interpretability module has to do nothing with the trained anamoly predictor. Just for the sake of simplicity, I had decided to use an altogether seperate new module that could be trained from scratch for user following. The objective was just to show as an example of building intepretable models.  Yes, indeed, one can always use the same deepcnn or lstmaenn model that was used to detect anamolies to get the interpretations of the inferences with the interpretable module. Hope it clarifies your query.
